GenomicMedLab/cool-seq-tool

- tests/unit/test_uta_tools.py
- uta_tools/uta_tools.py
@ahwagner recommendations:
transcript_to_genomic --> transcript_to_genomic_coordinates
genomic_to_transcript --> genomic_to_transcript_exon_coordinates
> Renaming methods

- Pipfile
- requirements-dev.txt
- requirements.txt
- setup.cfg
- uta_tools/data_sources/uta_database.py
Realized this isn't actually needed. We're fine just setting environment variables in EB.
> Revert secret for db

- uta_tools/data_sources/uta_database.py
> Clean up connection args, try fixing connection error

- tests/unit/test_mane_transcript.py
- tests/unit/test_mane_transcript_mappings.py
- tests/unit/test_uta_tools.py
- uta_tools/data_sources/mane_transcript.py
- uta_tools/data_sources/uta_database.py
- uta_tools/uta_tools.py
- uta_tools/version.py
> Issue 59: Updating tests + fixes coordinate bugs

- .flake8
- tests/unit/test_mane_transcript.py
- tests/unit/test_uta_database.py
- uta_tools/data_sources/mane_transcript.py
- uta_tools/data_sources/uta_database.py
- uta_tools/version.py
> Issue 68: Fix mane transcript bugs

- requirements-dev.txt
- requirements.txt
- tests/unit/test_uta_tools.py
- uta_tools/uta_tools.py
- uta_tools/version.py
> Issue 70: Fix index error when getting tx exon

- .flake8
- tests/unit/test_mane_transcript.py
- uta_tools/data_sources/mane_transcript.py
- uta_tools/main.py
- uta_tools/version.py
Closes #92 
Also updated docs about returning inter-residue coords for get_mane_data endpoint
> refactor: get_mapped_mane_data should have inter-residue as default

- README.md
> docs: update readme for local data installations

- .gitignore
- README.md
- cool_seq_tool/app.py
- cool_seq_tool/data/data_downloads.py
- cool_seq_tool/paths.py
cleaned up version of #162. Small changes to logging and configuration with environment variables, and add some descriptiveness in a few places.
> feat: clean up file download behavior and descriptions

- cool_seq_tool/data_sources/transcript_mappings.py
> revert: support for LRG sequences

- cool_seq_tool/app.py
- cool_seq_tool/data_sources/uta_database.py
- tests/unit/test_mane_transcript.py
> build: use standard lib urlparse

- cool_seq_tool/mappers/mane_transcript.py
- cool_seq_tool/sources/mane_transcript_mappings.py
- tests/sources/test_mane_transcript_mappings.py
Close #212 
* Now returns MANE Select and then MANE Plus Clinical
> refactor!: `get_gene_mane_data` sorted by desc MANE_Status

- src/cool_seq_tool/sources/uta_database.py
* Only call unique function if DataFrame is not empty
> fix: polars InvalidOperationError

- docs/source/transcript_selection.rst
- docs/source/usage.rst
- src/cool_seq_tool/app.py
- src/cool_seq_tool/mappers/__init__.py
- src/cool_seq_tool/mappers/alignment.py
- src/cool_seq_tool/mappers/exon_genomic_coords.py
- src/cool_seq_tool/mappers/mane_transcript.py
- src/cool_seq_tool/sources/__init__.py
- src/cool_seq_tool/sources/mane_transcript_mappings.py
- src/cool_seq_tool/sources/uta_database.py
close #221
* UTADatabase -> UtaDatabase
* MANETranscript -> ManeTranscript
* MANETranscriptMappings -> ManeTranscriptMappings
> refactor!: fix class naming

- pyproject.toml
- src/cool_seq_tool/version.py
close #256 . Followed https://setuptools.pypa.io/en/latest/userguide/datafiles.html#subdirectory-for-data-files
Notes:
* Includes transcript_mappings.tsv
> fix: include package data

- src/cool_seq_tool/version.py
It did not need to be bumped. Oops
> fix: package version

- .pre-commit-config.yaml
- pyproject.toml
- src/cool_seq_tool/version.py
close #271 
@jarbesfeld once this is merged, please update your branch
> build: pin ruff to v0.2.0

- src/cool_seq_tool/mappers/mane_transcript.py
> fix: don't use deprecated columns param

- pyproject.toml
> build: pin polars 1.0

- src/cool_seq_tool/__init__.py
- src/cool_seq_tool/app.py
- src/cool_seq_tool/handlers/seqrepo_access.py
- src/cool_seq_tool/mappers/exon_genomic_coords.py
- src/cool_seq_tool/mappers/mane_transcript.py
- src/cool_seq_tool/routers/default.py
- src/cool_seq_tool/routers/mane.py
- src/cool_seq_tool/routers/mappings.py
- src/cool_seq_tool/sources/mane_transcript_mappings.py
- src/cool_seq_tool/sources/uta_database.py
- src/cool_seq_tool/utils.py
I could've sworn that I've made this PR like 7 times already.
> fix: use correct logging setup

- src/cool_seq_tool/sources/uta_database.py
* Explicitly specify orientation for pl.DataFrame
> fix: resolve DataOrientationWarning for pl.DataFrame

- src/cool_seq_tool/mappers/exon_genomic_coords.py
@korikuzma we should put out a new release after this goes through
> fix: correct strand typo

- tests/mappers/test_mane_transcript.py
close #261
* also updates mock / test case
> fix(test): remove fixture decorator from get_prioritized_transcripts_from_gene

- docs/source/conf.py
probably gonna have to fix this everywhere fml
> docs: fix source link

- src/cool_seq_tool/mappers/alignment.py
- src/cool_seq_tool/mappers/exon_genomic_coords.py
- src/cool_seq_tool/mappers/mane_transcript.py
- src/cool_seq_tool/schemas.py
- src/cool_seq_tool/sources/uta_database.py
- tests/conftest.py
- tests/mappers/test_mane_transcript.py
- tests/sources/test_uta_database.py
* Only focused on `UtaDatabase` for now
* `alt_pos_change` was renamed to `pos_change`
Created `staging` branch for these changes, just in case other issues wanted to be addressed / released.
> feat!: Return Pydantic models instead of dicts in UtaDatabase

- src/cool_seq_tool/mappers/exon_genomic_coords.py
- src/cool_seq_tool/sources/uta_database.py
- tests/conftest.py
- tests/mappers/test_exon_genomic_coords.py
- tests/sources/test_uta_database.py
addresses #224
* initial work for cleaning up exon coord data retrieval
Still working on creating smaller PRs from #346 . There's some other exon code that will be removed in later PRs.
> feat!: remove `UtaDatabase.get_tx_exons` + cleanup exon work

- src/cool_seq_tool/mappers/exon_genomic_coords.py
- tests/conftest.py
- tests/mappers/test_exon_genomic_coords.py
> refactor!: rename `ExonCoord` to `_ExonCoord` to indicate internal use

- src/cool_seq_tool/mappers/exon_genomic_coords.py
- tests/mappers/test_exon_genomic_coords.py
> Do not require gene when genomic accession and transcript are provided to genomic_to_tx_segment

- src/cool_seq_tool/sources/mane_transcript_mappings.py
> Ensure proper gene symbol comparison

- src/cool_seq_tool/mappers/exon_genomic_coords.py
- tests/mappers/test_exon_genomic_coords.py
> fix!: Expect user to supply valid, case-sensitive HGNC symbol

- pyproject.toml
close #392
This is blocking for MetaKB
> build: pin `wags-tails` to `~= 0.2.2`

- src/cool_seq_tool/mappers/mane_transcript.py
- tests/mappers/test_mane_transcript.py
> fix: resolve TypeError by using property accessor

- src/cool_seq_tool/mappers/exon_genomic_coords.py
- tests/mappers/test_exon_genomic_coords.py
closes #396 
- Given a transcript, genomic accession, and genomic breakpoint location, checks if the breakpoint falls between the minimum `alt_start_i` and maximum `alt_end_i` values
- We want to check if a breakpoint falls between these values when constructing a `TranscriptSegmentElement` in FUSOR
> feat!: Change breakpoint validation function

- pyproject.toml
I'm working on updating MetaKB to the latest GKS specs and was getting dependency conflicts
> build: bump wags-tails to latest version (v0.3.2)

- pyproject.toml
I forgot we already used polars
> build: remove duplicate polars dep

- src/cool_seq_tool/mappers/alignment.py
- src/cool_seq_tool/mappers/feature_overlap.py
- src/cool_seq_tool/mappers/mane_transcript.py
Wanted to mess around with [ty](https://github.com/astral-sh/ty)
> fix(types): resolve type errors
