GenomicMedLab/cool-seq-tool

uta_tools/data_sources/uta_database.py

* Extract "exists" value from `genomic_table_exists` query
* Fix `CREATE_INDEX` queries typo
* Add factory-style method to `UTADatabase` -- I'm not horribly attached to this but I think it's helpful to provide when classes have some initialization requirements outside of `__init__`
I wasn't sure of a good way to write tests without some kind of mock DB class, let me know if you have thoughts

Fix some create_genomic_table() issues + add DB create() method

---

cool_seq_tool/cool_seq_tool.py
cool_seq_tool/data_sources/gene_normalizer.py

Close #129 
- This allows for a current query handler instance to be used, rather than always creating a new instance

feat: accept current gene normalizer query handler

---

README.md
cool_seq_tool/__init__.py
cool_seq_tool/cool_seq_tool.py
cool_seq_tool/data_sources/mane_transcript_mappings.py
cool_seq_tool/data_sources/seqrepo_access.py
cool_seq_tool/data_sources/transcript_mappings.py

Close #131 
Notes:
- SEQREPO_DATA_PATH, TRANSCRIPT_MAPPINGS_PATH, MANE_SUMMARY_PATH, and LRG_REFSEQGENE_PATH paths can now be set using env vars
- Updates type hints / docstrings for these to be Path rather than string

refactor: allow static file paths to be set via env var

---

README.md
cool_seq_tool/app.py
cool_seq_tool/data_sources/uta_database.py

Users should set the postgres password in the connection URL, rather than via a separate env var or method param. Now `uta_database.py` is only 1152 lines long!

feat!: remove separate UTA password param

---

.github/workflows/release.yml

- Followed https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
- Did not include [Signing the distribution packages](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#signing-the-distribution-packages)
- In `publish-to-pypi`, removed `if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes` since we only make a release when a GH release is created.

cicd: update release.yaml (publish python distribution to pypi)

---

cool_seq_tool/sources/uta_database.py
tests/sources/test_uta_database.py

…en gene, regardless of pos
close #170 
made a new pr because I have no idea what's going on with the old branch, so I wanted a fresh one off main

feat: make positions optional in get_transcripts_from_gene

---

Pipfile
cool_seq_tool/data/data_downloads.py
cool_seq_tool/data_sources/__init__.py
cool_seq_tool/data_sources/feature_overlap.py
cool_seq_tool/paths.py
cool_seq_tool/schemas.py
cool_seq_tool/version.py
setup.cfg
tests/unit/test_feature_overlap.py

Address #216 for 0.1.x . This is needed for variation manuscript
Notes:
* Add class (`FeatureOverlap`) for getting cds overlap
* Only supports GRCh38 input
* Returns VRS Sequence Locations 
* `get_mane_summary` --> `get_mane`
* Now can additionally download MANE RefSeq GFF file

feat: get cds overlap given chromosome, start, + stop

---

README.md
setup.cfg

Wasn't entirely sure what the URL would end up being until it built, so adding these now that the other docs PR is merged

docs: add README links

---

src/cool_seq_tool/mappers/mane_transcript.py
src/cool_seq_tool/version.py

@jsstevenson PR noticed this since there are CI tests for python >= 3.8

fix: StrEnum to Enum for python < 3.11

---

.github/workflows/checks.yml
docs/source/changelog.rst
docs/source/conf.py
docs/source/index.rst
pyproject.toml

https://coolseqtool--259.org.readthedocs.build/en/259/changelog.html
was thinking about the VRS-Python changelog, did some googling, decided to test it out here. You need to generate a GitHub API access token but if the repo in question is public, it needs 0 permissions (you leave everything unchecked) (unfortunately it will expire after like a year or something).

docs: add generated changelog

---

README.md

I updated the RTD settings to turn off language-specific docs (I don't foresee us translating to other languages any time soon) and it broke the links

docs: fix readme links to docs

---

docs/source/usage.rst
pyproject.toml
src/cool_seq_tool/sources/uta_database.py
src/cool_seq_tool/version.py
tests/sources/test_uta_database.py

build: replace pyliftover with agct to improve performance

---

docs/source/conf.py
src/cool_seq_tool/schemas.py

The existing lil ASCII table in the ResidueMode docstring wouldn't render properly in Sphinx nor in markdown-style blocks (eg in VSCode popups). This adds an RST table and retains the ASCII table but puts it in a code block, and then strips the ASCII table out when constructing the Sphinx autodoc page.
Broken:
Fixed in VSCode (it auto ignores all of the RST stuff):
Fixed in Sphinx docs:

docs: fix residue mode illustration rendering

---

src/cool_seq_tool/mappers/exon_genomic_coords.py

*genomic_to_transcript_exon_coordinates example should use alt_ac instead of chromosome for an accession

fix(docs): correct kwarg in docstring example

---

src/cool_seq_tool/app.py
src/cool_seq_tool/resources/data_files.py
src/cool_seq_tool/sources/mane_transcript_mappings.py
src/cool_seq_tool/sources/transcript_mappings.py

* Optionally, suppress checks for static files being up-to-date, and instead just go with the latest available data file. IE, pass a value to the wags-tails `from_local` param.
Making this a separate PR to merge into the resource acquisition branch just because it's a thought that I had kind of late.

feat: enable suppression of latest resource check

---

pyproject.toml
src/cool_seq_tool/handlers/seqrepo_access.py
src/cool_seq_tool/mappers/exon_genomic_coords.py
src/cool_seq_tool/sources/uta_database.py
src/cool_seq_tool/utils.py
tests/handlers/test_seqrepo_access.py
tests/mappers/test_exon_genomic_coords.py
tests/sources/test_uta_database.py

* Use common processing methods for all cases of chromosome args that transforms bare number strings like `"7"` into UCSC-style prefixed strings like `"chr7"`. 
* Fills in some vagueries surrounding chromosome/accession usage in documentation

feat: consistently handle bare and prefixed chromosome numbering

---

src/cool_seq_tool/sources/uta_database.py

close #104
* change log level from warning to error

fix: update handling ClientErrors when getting aws secret value

---

docs/source/reference/index.rst
docs/source/usage.rst
src/cool_seq_tool/app.py
src/cool_seq_tool/mappers/__init__.py
src/cool_seq_tool/mappers/exon_genomic_coords.py
src/cool_seq_tool/mappers/liftover.py
src/cool_seq_tool/mappers/mane_transcript.py
src/cool_seq_tool/resources/status.py
src/cool_seq_tool/sources/uta_database.py
tests/conftest.py
tests/mappers/test_liftover.py
tests/mappers/test_mane_transcript.py
tests/sources/test_uta_database.py

close #158
* Remove LiftOver from UtaDatabase class
* LiftOver separated into its own class
* ManeTranscript and ExonGenomicCoordsMapper now take liftover as param in init method
This PR only focuses on separating these two classes. I think a new issue could be made for cleaning up these classes.

refactor!: move liftover to separate module

---

src/cool_seq_tool/mappers/exon_genomic_coords.py
tests/mappers/test_exon_genomic_coords.py

close #313 
These had become kind of scattered, and each "warning" would insta-return rather than waiting to see if other inputs were also invalid. I wouldn't say that this is an exhaustive overhaul but it moves a check closer to the original call and also lets other checks occur where it seems easy to let them run.

feat: validate all inputs at once

---

docs/source/contributing.rst
docs/source/install.rst
pyproject.toml

* `tests` -> `test`
Just to be consistent with template repo

chore: rename optional dependency

---

src/cool_seq_tool/mappers/mane_transcript.py
tests/mappers/test_mane_transcript.py

close #229
* `ManeTranscript._validate_index` -> `ManeTranscript.validate_index`
* `ManeTranscript._get_reading_frame` -> `ManeTranscript.get_reading_frame`

feat: make methods in `ManeTranscript` public

---

docs/source/usage.rst

* Cool-Seq-Tool does not use any VRS models and only SeqRepo is used from VRS-Python

docs: remove VRS schema support section

---

src/cool_seq_tool/mappers/exon_genomic_coords.py
tests/conftest.py
tests/mappers/test_exon_genomic_coords.py

addresses #224
@jsstevenson not sure what our convention is if a breaking change occurs in private methods. Theoretically, since they have a leading underscore they are meant to be internal but if people still choose to use these methods they should be aware? Kept going back and forth on this (as I always do with conventional commits it feels like).

refactor: rename `is_start` kwarg in private methods to `is_seg_start`

---

src/cool_seq_tool/mappers/exon_genomic_coords.py
tests/mappers/test_exon_genomic_coords.py

* Remove `uta_db.validate_genomic_ac` check in `_genomic_to_tx_segment`. `_get_genomic_ac_gene` already handles this check.

refactor: remove duplicate `genomic_ac` check

---

src/cool_seq_tool/mappers/exon_genomic_coords.py
tests/mappers/test_exon_genomic_coords.py

closes #380 
This checks to see if a coordinate occurs before or after the transcript range when selecting the adjacent exon. Previously, this would iterate through the entire exon list, leading to very large offsets and incorrect adjacent exon selection

fix!: Add support for checking before/after transcript boundaries

---

src/cool_seq_tool/mappers/exon_genomic_coords.py
tests/conftest.py
tests/mappers/test_exon_genomic_coords.py

fix: Check to see if there is only one exon in a transcript when selecting the adjacent exon

---

docs/source/contributing.rst
docs/source/install.rst
pyproject.toml

chore!: rename optional dependency

---

docs/source/install.rst
docs/source/usage.rst
src/cool_seq_tool/sources/uta_database.py

close #399
* Update default value for `UTA_DB_URL` to point to latest UTA version

feat: update seqrepo and uta version to 20241220

---

src/cool_seq_tool/mappers/exon_genomic_coords.py
tests/mappers/test_exon_genomic_coords.py

feat!: Add strand in GenomicTxSeg output

---

docs/source/reference/index.rst
pyproject.toml
src/cool_seq_tool/mappers/__init__.py
src/cool_seq_tool/mappers/feature_overlap.py
src/cool_seq_tool/resources/data_files.py
src/cool_seq_tool/schemas.py
tests/handlers/test_feature_overlap.py

close #411
Initial work for this was done in PR #217
Changes: I replaced pandas with polars, used VRS 2.0 models

feat: add back FeatureOverlap class

---

.gitignore

Vscode creates files in `.vscode` when the project is opened. These should be ignored by version control.

chore: add vscode to gitignore

---

src/cool_seq_tool/mappers/exon_genomic_coords.py
tests/mappers/test_exon_genomic_coords.py

Closes #422
A new field called `is_exonic` is added which indicates whether or not the position at the start or end of a transcript segment occurs on an exon.

feat: Add `is_exonic` field to transcript segment output

---

pyproject.toml
src/cool_seq_tool/resources/status.py
src/cool_seq_tool/sources/uta_database.py
tests/sources/test_uta_database.py

At present, the status check logs the DB URL, including the password.
This PR uses a helper function from pip to redact the password from the URLs, making them safe to log.
After this change, this is what the log messages look like:
```
ERROR:cool_seq_tool.resources.status:Encountered error instantiating UTA at URI postgresql://uta_admin:****@localhost:5432/uta/uta_20241220
```
Closes #429

fix: Redact auth from DB url in status check
